---

- name: Check if firewalld is up and running
  include_role:
    name: tendrl-ansible.tendrl-server
    tasks_from: firewalld-check

- name: Enable port for etcd
  firewalld:
    port=2379/tcp
    permanent=yes
    state=enabled
    immediate=true

- name: Enable port for graphite
  firewalld:
    port=2003/tcp
    permanent=yes
    state=enabled
    immediate=true

- name: Enable port for Graphite web
  firewalld:
    port=10080/tcp
    permanent=yes
    state=enabled
    immediate=true

- name: Enable port for http
  firewalld:
    port=80/tcp
    permanent=yes
    state=enabled
    immediate=true

- name: Enable port for grafana server
  firewalld:
    port=3000/tcp
    permanent=yes
    state=enabled
    immediate=true

- name: Enable port for tendrl-monitoring-integration (grafana alerts callback)
  firewalld:
    port=8789/tcp
    permanent=yes
    state=enabled
    immediate=true
