---
- hosts: all
  become: yes
  tasks:
    - name: Bounce Services
      systemd:
        name: tendrl-*
        state: restarted
    - name: Ensure services started
      systemd:
        name: tendrl-*
        state: started
