---

- hosts: gluster-servers

  become: true

  tasks:
    - name: Install gdeploy
      yum:
        name: gdeploy
        state: present

    - name: Generate gdeploy.conf
      template:
        src: gdeploy-{{ provider }}.conf.j2
        dest: "/tmp/gdeploy.conf"

    - name: Run GDeploy
      shell: 'gdeploy -c /tmp/gdeploy.conf'

    - name: Remove epel repo
      yum_repository:
        name: epel
        file: epel
        state: absent

    - name: Remove epel-testing repo
      yum_repository:
        name: epel
        file: epel-testing
        state: absent

- hosts: tendrl-server

  become: true

  tasks:
    - name: Remove epel repo
      yum_repository:
        name: epel
        file: epel
        state: absent

    - name: Remove epel-testing repo
      yum_repository:
        name: epel
        file: epel-testing
        state: absent
...
